### ISSUE TITLE
Unexpected behaviour: CONFIG file is modified by the software

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/manual-correction#86]
After figuring out #85, I manually created a YML file that looked like this:

```yaml
FILES_LABEL:
- sub-Marseille1_UNIT1.nii.gz
- sub-MGH1_UNIT1.nii.gz
- sub-MNI1_UNIT1.nii.gz
- sub-MPI1_UNIT1.nii.gz
- sub-NTNU1_UNIT1.nii.gz
- sub-NYU1_UNIT1.nii.gz
- sub-UCL1_UNIT1.nii.gz
```

After running `manual_correction.py`, I wanted to document in [another project](https://github.com/spinal-cord-7t/coil-qc-code/issues/27) how I did it. So I was about to package my config file, but... what a surprised: it has been modified by the software. It now looks like this:

```yaml
CORR_LABEL:
- sub-Marseille1_UNIT1.nii.gz
- sub-MGH1_UNIT1.nii.gz
- sub-MNI1_UNIT1.nii.gz
- sub-MPI1_UNIT1.nii.gz
- sub-NTNU1_UNIT1.nii.gz
- sub-NYU1_UNIT1.nii.gz
- sub-UCL1_UNIT1.nii.gz
FILES_LABEL: []
```

Modifying config file is highly unexpected and should not happen.

**Comment by valosekj** [comment]
Thanks for reporting this. The modification of the YML config file was introduced in https://github.com/spinalcordtoolbox/manual-correction/pull/57 to track which files have been modified. It is useful, for example, when a user needs to pause/restart corrections. The correction process in such a case continues from the last non-corrected subject instead of starting from the beginning. 

But I agree that it might be confusing. I have an open issue about it: https://github.com/spinalcordtoolbox/manual-correction/issues/62

Relevant comment from Nathan here: https://github.com/spinalcordtoolbox/manual-correction/pull/57#issuecomment-1688885629

**Comment by jcohenadad** [comment]
Maybe a <CONFIG>.tmp should be created?

Also, this behaviour should appear as a subsection in the README. In general (bigger issue), the README section should be self-contained, and users should not have to go to the example section to understand how to use this software.

**Comment by valosekj** [comment]
Potential idea:

The original config file would be kept as it is (without any filename or content modifications), for example, `config.yml`:

```yml
FILES_LABEL:
- sub-Marseille1_UNIT1.nii.gz
- sub-MGH1_UNIT1.nii.gz
- sub-MNI1_UNIT1.nii.gz
- sub-MPI1_UNIT1.nii.gz
- sub-NTNU1_UNIT1.nii.gz
- sub-NYU1_UNIT1.nii.gz
- sub-UCL1_UNIT1.nii.gz
```

After running and stopping `manual_correction.py`, a new copy of the config file tracking the corrected files would be created, for example, `<CONFIG>.tmp`:

```yml
CORR_LABEL:
- sub-Marseille1_UNIT1.nii.gz
- sub-MGH1_UNIT1.nii.gz
- sub-MNI1_UNIT1.nii.gz
FILES_LABEL:
- sub-MPI1_UNIT1.nii.gz
- sub-NTNU1_UNIT1.nii.gz
- sub-NYU1_UNIT1.nii.gz
- sub-UCL1_UNIT1.nii.gz
```

If the user wanted to continue from the last modified file, they would enter the path to the `<CONFIG>.tmp` file. 
At the same time `manual_correction.py` will contain a condition to overwrite `<CONFIG>.tmp` file (and not create `<CONFIG>.tmp.tmp`) when rerunning the script.
